on: push

jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements-dev.txt --no-deps
    - run: pip install -r requirements.txt --no-deps
    - run: python -m pylint llmio examples

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements-dev.txt --no-deps
    - run: pip install -r requirements.txt --no-deps
    - run: python -m mypy .

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements-dev.txt --no-deps
    - run: pip install -r requirements.txt --no-deps
    - run: make test

  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements-dev.txt --no-deps
    - run: pip install -r requirements.txt --no-deps
    - run: python -m black . --check

  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements-dev.txt --no-deps
    - run: pip install -r requirements.txt --no-deps
    - run: ruff check .
