name: Publish Python distribution to PyPI

on:
  release:
    types: [released]

jobs:
  build:
    name: Publish Python distribution to PyPI.
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/llmio/

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures tags are also fetched
      - uses: astral-sh/setup-uv@v6
      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Build
        run: uv build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
